language: node_js
os:
  - linux
  - osx
node_js:
  - "stable"
  - "5.4.1"
  - "5.3"
  - "5.2"
  - "5.1"
  - "5.0"
  - "4.2"
script: "node test/lint.js"
sudo: false
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "5.3"
    - node_js: "5.2"
    - node_js: "5.1"
    - node_js: "5.0"
    - node_js: "4.2"
